spring:
  #  # H2
  #  datasource:
  #    url: jdbc:h2:tcp://localhost/~/stockManager
  #    username: sa
  #    password:
  #    driver-class-name: org.h2.Driver

  #  # mariaDB
  #  datasource:
  #    driverClassName: org.mariadb.jdbc.Driver
  #    url: jdbc:mariadb://localhost:3306/stockManager?characterEncoding=UTF-8&serverTimezone=UTC

  # mysql
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/stockManager?allowPublicKeyRetrieval=true&useSSL=false

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    #      ddl-auto: none
    properties:
      dialect:
        org.hibernate.dialect.MySQL5InnoDBDialect
      hibernate:
        #        show_sql: true
        format_sql: true
        default_batch_fetch_size: 100
  rsocket:
    server:
      port: 80

logging:
  config: classpath:logback-spring.xml
  level:
    org.hibernate.SQL: debug
    org.springframework.security: DEBUG
#    org.hibernate.type: trace